title: Christopher M Lee
description: Chris's Work Portolio
theme: just-the-docs

url: https://christonifter.github.io/
logo: "/assets/images/mug.jpg"

aux_links:
  Linkedin: https://www.linkedin.com/in/cml-neuro/
